export const GET_UNVERIFIED_DOCTORS_LIST = "admin/unverifieddoctorslist";
export const GET_DOCTOR_VIEW_DETAILS = "admin/doctorviewdetails";
export const VERIFY_DOCTOR_PROFILE = "admin/verifydoctorprofile";
export const GET_PAGED_PATIENTS_LIST = "admin/pagedpatientslist";
export const GET_PAGED_DOCTORS_LIST = "admin/pageddoctorslist";
export const GET_PATIENT_VIEW_DETAILS = "admin/patientviewdetails";
export const GET_ALL_REFUND_DATA = "api/GetAllRefundData";
export const APPROVE_REFUND = "api/ApproveRefund";
export const GET_ALL_UNPROCESSED_WITHDRAW = "admin/allunprocessedwthdraw";
export const APPROVE_WITHDRAW = "api/ApproveWithdraw";
export const GET_ALL_REVIEWS = "api/GetAllReviews";
export const DELETE_REVIEW_BY_ID = "api/DeleteReviewById";
export const GET_ALL_COMMISSION = "admin/allcommission";
export const SAVE_DOCTOR_COMMISSION = "api/SaveDoctorCommission";
export const GET_FINANCE_DATA = "admin/financedata";
export const MARK_AS_PAID = "api/MarkAsPaid";
export const GET_DOCTOR_PAYMENT = "api/GetDoctorPayment";
export const SAVE_CMS_PAGE = "SaveCMSPage";
export const GET_LANGUAGE_ALL_MESSAGES = "GetLanguageAllMessages";
export const SAVE_LANGUAGE_LABEL_DATA = "SaveLanguageLabelData";
export const GET_PATIENT_QUESTIONNAIRE_LANGUAGE =
  "GetPatientQuestionnaireLanguage";
export const SAVE_PATIENT_QUESTIONNAIRE_LANGUAGE =
  "SavePatientQuestionnaireLanguage";
export const GET_ALL_PHYSICIAN_SERVICE_DETAIL = "admin/allphysicianservice";
export const SAVE_PHYSICIAN_SERVICE = "admin/physicianservice";
export const GET_ALL_LANGUAGE_DETAIL = "admin/allLanguage";
export const SAVE_LANGUAGE = "admin/language";
export const SAVE_WEBSITE_LANGUAGE_ID = "admin/websitelanguageid";
