export const GET_UNVERIFIED_DOCTORS_LIST = "api/GetUnVerifiedDoctorsList";
export const GET_DOCTOR_VIEW_DETAILS = "api/GetDoctorViewDetails";
export const VERIFY_DOCTOR_PROFILE = "api/VerifyDoctorProfile";
export const GET_PAGED_PATIENTS_LIST = "api/GetPagedPatientsList";
export const GET_PAGED_DOCTORS_LIST = "api/GetPagedDoctorsList";
export const GET_PATIENT_VIEW_DETAILS = "api/GetPatientViewDetails";
export const GET_ALL_REFUND_DATA = "api/GetAllRefundData";
export const APPROVE_REFUND = "api/ApproveRefund";
export const GET_ALL_UNPROCESSED_WITHDRAW = "api/GetAllUnprocessedWithdraw";
export const APPROVE_WITHDRAW = "api/ApproveWithdraw";
export const GET_ALL_REVIEWS = "api/GetAllReviews";
export const DELETE_REVIEW_BY_ID = "api/DeleteReviewById";
export const GET_ALL_COMMISSION = "api/GetAllCommission";
export const SAVE_DOCTOR_COMMISSION = "api/SaveDoctorCommission";
export const GET_FINANCE_DATA = "api/GetFinanceData";
export const MARK_AS_PAID = "api/MarkAsPaid";
export const GET_DOCTOR_PAYMENT = "api/GetDoctorPayment";
export const SAVE_CMS_PAGE = "SaveCMSPage";
export const GET_LANGUAGE_ALL_MESSAGES = "GetLanguageAllMessages";
export const SAVE_LANGUAGE_LABEL_DATA = "SaveLanguageLabelData";
export const GET_PATIENT_QUESTIONNAIRE_LANGUAGE =
  "GetPatientQuestionnaireLanguage";
export const SAVE_PATIENT_QUESTIONNAIRE_LANGUAGE =
  "SavePatientQuestionnaireLanguage";
export const GET_ALL_PHYSICIAN_SERVICE_DETAIL = "GetAllPhysicianServiceDetail";
export const SAVE_PHYSICIAN_SERVICE = "SavePhysicianService";
export const GET_ALL_LANGUAGE_DETAIL = "GetAllLanguageDetail";
export const SAVE_LANGUAGE = "SaveLanguage";
export const SAVE_WEBSITE_LANGUAGE_ID = "SaveWebsiteLanguageId";
